### ISSUE TITLE
click event fires twice on ios devices

### ISSUE THREAD

**Issue by dm-grinko** [kadoshms/ionic2-autocomplete#39] opened 2017-05-11 12:05 UTC
I have spend a lot of time to find solution.
This closed issue helped me to understand that problem is in your plugin.
https://github.com/driftyco/ionic/issues/10520

By the way All works good with browser and with android

**Comment by kadoshms** [comment] 2017-05-12 09:32
Fixed in 1.4.3-beta (commit b81f56b4d269d731b84a1e6c3d900a1825988cca)

**Comment by dm-grinko** [comment] 2017-05-15 09:34
thank you

**Comment by dm-grinko** [comment] 2017-05-15 13:09
Unfortunately you don't fixed it

**Comment by kadoshms** [comment] 2017-05-15 13:17
Can you please elaborate more? 
How can I reproduce this?
When I tested on an iOS simulator, it didn't fire twice.

**Comment by kadoshms** [comment] 2017-05-15 13:36
Anyway, is there a way to reproduce this bug?

**Comment by kadoshms** [comment] 2017-05-15 15:54
@dm-grinko I pushed a possible fix to the issue df59bfbc20365fb7ee57c27693e61fc20061c90b
Since I could not reproduce this issue myself, could you please try to apply this change in your project? 
(You can do that by cloning this repo, switching to branch `fix-#39` ,running `npm run prepublish`, and copying the whole directory to your `node_modules`, or simply download the attached file).

If this works for you, please let me know so I'll publish it.
[ionic2-autocomplete.zip](https://github.com/kadoshms/ionic2-autocomplete/files/1001600/ionic2-autocomplete.zip)

**Comment by kadoshms** [comment] 2017-05-17 08:29
Fixed and will be publish on next release.

**Closed by kadoshms** 2017-05-17 08:29 UTC
Labels: bug
