### ISSUE TITLE
on itemSelected requires  stopPropagation in order to prevent clicking another item/button behind

### ISSUE THREAD

**Issue by sabrio** [kadoshms/ionic2-autocomplete#75] opened 2017-07-09 09:07 UTC
I am having issue with `(itemSelect)` while I am select an item, it also triggers a click behind the list. Is there a way to event.stopPropagation()?

**Comment by kadoshms** [comment] 2017-07-11 19:11
Unfortunately not in the current version, but I will add a support for that in the next release.

**Comment by kadoshms** [comment] 2017-07-13 15:12
fixed in 64063f45dba0652088b0adc6686653f96d631cf1

**Closed by kadoshms** 2017-07-13 15:12 UTC
Labels: enhancement, question

**Comment by sabrio** [comment] 2017-07-26 15:02
@kadoshms the issue seems to occur again, I am testing it on Android and it does occur. Can you please return the event somehow?

**Comment by webmanblog** [comment] 2017-08-24 11:03
@kadoshms confirmed, the issue is still outstanding, at least on Android platform..

**Comment by JahBrewski** [comment] 2017-11-22 22:53
@kadoshms Also seeing this bug. Is there a fix? This almost makes the plugin unusable.

**Comment by renanmoraes** [comment] 2018-06-30 23:14
@kadoshms  Really still occurs
