### ISSUE TITLE
Cannot get focus when tapping on the ion-auto-complete on Android phone.

### ISSUE THREAD

**Issue by wuzp1230** [kadoshms/ionic2-autocomplete#132] opened 2017-12-07 08:45 UTC
I tried to put an <ion-auto-complete> in a <ion-col> or a <ion-content> and built it to an apk. When I tried to tap on the <ion-auto-complete>,the input cursor don't show,keyboard don't pop up either. But when I run on Chrome with DevTool on my computer,the input cursor works well. My devices: an android 6.0 and an android 7.1.2, niether works. I also tried to add a (click) to activate the setFocus(), but nothing solved. Whats wrong? Looking forward to your reply.
<ion-auto-complete style="width: 100%;" [options]="{ placeholder:approvalPersonSelected}" #searchbar  (click)="setSearchBarFocus()"  (itemSelected)="itemSelected($event)" (itemsShown)="itemsShown($event)" (itemsHidden)="itemsHidden($event)"  [dataProvider]="completeTestService"></ion-auto-complete>

**Comment by Exormeter** [comment] 2017-12-07 15:21
I might have the same issue on iOS, do you get the keyboard if you tap the input field rapidly?

**Comment by wuzp1230** [comment] 2017-12-07 16:26
I can get the keyboard when I long press the input.Then a little 'paste' tip comes up.It's unfriendly.

**Comment by kadoshms** [comment] 2017-12-16 13:36
Duplicate of #134

**Closed by kadoshms** 2017-12-16 13:36 UTC
